# Generated by Django 2.2.3 on 2019-11-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorModel',
            fields=[
                ('d_name', models.CharField(max_length=30)),
                ('d_user_id', models.CharField(max_length=30)),
                ('d_password', models.CharField(max_length=30)),
                ('d_gender', models.CharField(max_length=30)),
                ('d_mail', models.CharField(max_length=30)),
                ('d_contact_no', models.IntegerField(primary_key=True, serialize=False)),
                ('d_last_donated', models.DateField()),
                ('d_blood_group', models.CharField(max_length=30)),
                ('d_weight', models.FloatField()),
                ('d_state', models.CharField(max_length=30)),
                ('d_city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('org_name', models.CharField(max_length=30)),
                ('org_user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('org_password', models.CharField(max_length=30)),
            ],
        ),
    ]
